# Generated by Django 4.1.5 on 2023-02-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuapp', '0002_contact_testimonial_delete_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simage', models.ImageField(default='service.jpg', upload_to='')),
                ('stitle', models.CharField(max_length=255)),
                ('sdescription', models.TextField(max_length=255)),
            ],
        ),
    ]
