# Generated by Django 4.1.5 on 2023-02-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuapp', '0004_remove_profile_status_profile_bio_profile_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eimage', models.ImageField(default='event.jpg', upload_to='Events Images')),
                ('ename', models.CharField(max_length=255)),
                ('edate', models.DateField(max_length=255)),
                ('etime', models.TimeField(max_length=255)),
                ('edescription', models.TextField(max_length=255)),
                ('elink', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, default='Normal Member', max_length=255, null=True),
        ),
    ]
