# Generated by Django 4.1.5 on 2023-02-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuapp', '0005_events_alter_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='eparlink',
            field=models.CharField(default='audio.mp3', max_length=255),
        ),
        migrations.AddField(
            model_name='events',
            name='epytlink',
            field=models.CharField(default='video.youtube', max_length=255),
        ),
    ]
