# Generated by Django 4.1.5 on 2023-02-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kwetuapp', '0008_alter_events_eparlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
